# permissions for end users to edit ldapserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ldapserviceaccount-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-sa-ldap
    app.kubernetes.io/part-of: k8s-sa-ldap
    app.kubernetes.io/managed-by: kustomize
  name: ldapserviceaccount-editor-role
rules:
- apiGroups:
  - ldapserviceaccount.lazos.me
  resources:
  - ldapserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldapserviceaccount.lazos.me
  resources:
  - ldapserviceaccounts/status
  verbs:
  - get
