---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ldapserviceaccount.lazos.me
  resources:
  - ldapserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldapserviceaccount.lazos.me
  resources:
  - ldapserviceaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - ldapserviceaccount.lazos.me
  resources:
  - ldapserviceaccounts/status
  verbs:
  - get
  - patch
  - update
